### ISSUE TITLE
[Suggestion] Could netherite be a little better?

### ISSUE THREAD

**Issue by ConqAra** [Benjamin-Norton/BetterTrims#1]
For the netherite you're putting on your trims, I feel like it should have an alternative or additional affect to the current one. It doesn't seem as strong or rewarding as the other ones for how hard the material is to get, especially if you wanted to put netherite trims on netherite.

**Comment by Benjamin-Norton** [comment]
Hmm, true. Not really sure what the effect could be. Open to ideas

**Comment by ConqAra** [comment]
Hmm, Netherite relates to nether-related things such as fire as we already discussed, but also is known to be sturdy. 

Maybe Armor trimming with netherite adds an additional 5% Fire Damage Reduction per Piece on top of its original effect? That would be cool and an alternative from using diamond trimming.

Another, lazier idea is to just make it the brute of the trims make it so it adds 5% Damage per piece?

**Comment by Benjamin-Norton** [comment]
5% Fire resistance per piece feels weak when the trim diamond just gives a flat 5% reduction to all damage, 25% per piece would result in a full set giving you a similar effect to fire resistance, or go with the damage idea, which does somewhat fit as netherite increases all tool/weapon damage by 1. Both feel appealing

**Comment by Benjamin-Norton** [comment]
Went with the 25% lava damage reduction

**Comment by ConqAra** [comment]
Maybe make it 12.5% per piece so a full set gives 50%? Being resistant to lava/fire is kinda too good, you still want to make use of fire resistance potions even in the late game

**Comment by ConqAra** [comment]
Maybe make it 12.5% per piece so a full set gives 50%? Being resistant to lava/fire is kinda too good, you still want to make use of fire resistance potions even in the late game.
