### ISSUE TITLE
Effects not applied when mounted

### ISSUE THREAD

**Issue by dadoirie** [Benjamin-Norton/BetterTrims#11]
Effects are not applied when mounted
![image](https://github.com/Benjamin-Norton/BetterTrims/assets/61109153/28502366-2dd5-4c17-9988-ddcbcde4c563)
![image](https://github.com/Benjamin-Norton/BetterTrims/assets/61109153/1fab7ce4-aee3-4035-b145-0d71d66d2945)
One screenshot crops from MiniHUD info is with a full set of Redstone armor (including Elytra) and the other is while not having that set equipped.

walking speed with set
![image](https://github.com/Benjamin-Norton/BetterTrims/assets/61109153/fe88138e-fca8-4c71-8dca-6822aa55d56b)

walking speed without set
![image](https://github.com/Benjamin-Norton/BetterTrims/assets/61109153/8a3bedb2-cbf8-4fde-a938-25f42a986fe8)

UPDATE: might not be that much of a issue and more of a convenience: would be nice if also the Elytra flight speed would get added up with the additional stats as with and without the redstone trim flying at full speed horizontally is pretty much at 33
![image](https://github.com/Benjamin-Norton/BetterTrims/assets/61109153/0498ecec-378e-4278-99e7-a0f1b7a98205)
as said - not really a issue, but considering that the Elytra has trims too and as Better Trims adds Elytra Trims compatibility it would just fit perfectly

**Comment by Benjamin-Norton** [comment]
I'm on vacation rn but I'll give this a look when I get back.

**Comment by Benjamin-Norton** [comment]
Added in 1.1.0
