### ISSUE TITLE
[Compat Request] compat with Guarding

### ISSUE THREAD

**Issue by dadoirie** [Benjamin-Norton/BetterTrims#14]
Possible compatibility with [Guarding!](https://modrinth.com/mod/guarding) as it has netherite shields which are trimable?

![image](https://github.com/Benjamin-Norton/BetterTrims/assets/61109153/79430f8b-655d-4f60-98d3-2a959cae7b71)

**Comment by Benjamin-Norton** [comment]
shouldn't be too difficult

**Comment by Benjamin-Norton** [comment]
Added in 1.2.0
