### ISSUE TITLE
[Material Request] Silver!

### ISSUE THREAD

**Issue by Ultimushadow** [Benjamin-Norton/BetterTrims#17]
Silver is quite a common material to be added but I specifically play with Clutter!

I was thinking something to do with magic damage. Silver is traditionally a pretty magic focused material I feel, so I could see adding increased magic resistance or magic damage, though I imagine the former would be more useful in a wider amount of situations as the player has pretty limited magic damage uses. I'm not entirely sure if your diamond damage reduction is _all_ damage or not, but if it is, then it could be switched to physical damage, or silver could provide a slightly higher rate of magic defense, but I think the former makes both materials more viable. The damage types affected would be indirect magic and magic, as well as potentially types like dragon breath.
The other option I thought of was silver's association with night/the moon. You could have slightly increased speed, strength, and resistance at night and in the End. I'm including the End here because the Nether has more association with Gold and it may as well be useful somewhere other than one of three dimensions half the time (less if you sleep). Because of that limited usefulness, I think the magic resistance is a better concept.

Other mods which add silver could have a similar effect, I don't actually have any so if there are other silver items I imagine this could be extended to them quite easily

Note, as of right now Clutter does not automatically make their silver ingot a trimmable material, but of course thanks to datapacks that's easily fixable and can be installed alongside the resource pack. Works with More Armor Trims too!
Find the packs mentioned and updates on silver as a trim being integrated into the Clutter mod rather than datapacks here: https://github.com/EmilsGithub/Clutter-Mod-Repository/issues/15

**Comment by Benjamin-Norton** [comment]
I can look into adding a silver material, I will probably keep its behaviour to more vanilla mechanics so I'll probably go with the buff at night idea, btw you should check out my other mod, [AllTheTrims](https://www.curseforge.com/minecraft/mc-mods/all-the-trims) which makes all items trim materials.

**Comment by Benjamin-Norton** [comment]
Added in 1.3.0, feel free to give feedback on the balance.

**Comment by Ultimushadow** [comment]
Thank you for your work! I'll playtest it a bit and let you know if I have any feedback!
Also, I know you mentioned sticking to vanilla mechanics, I just wanted to put out that magic damage resistance is actually a vanilla mechanic. I had a rabbit hole moment with all the armor and enchantment mechanics, and Protection does actually protect against the Magic damage type, pretty much every sub type of it. Since players can't get that kind of protection anywhere but the Prot enchant, I can see why you might label it not a vanilla mechanic, but I still suggest it as a possibility for a future implementation!
