### ISSUE TITLE
[Request] Add trim effects to tooltip

### ISSUE THREAD

**Issue by teleheel** [Benjamin-Norton/BetterTrims#19]
Would it be possible to add the trim's effect to the tooltip of the trimmed items? For example, a helmet upgraded with a redstone trim could have `+10% Movement Speed` next to or under the tooltip line that specifies the trim material. Maybe have the effect text in the same color as the material text. in order to convey that it is the material that is causing the effect.

**Comment by Benjamin-Norton** [comment]
Yup, I can add that, probably should've already.

**Comment by Benjamin-Norton** [comment]
Added in 1.3.0
