### ISSUE TITLE
Suggestion: Trim Templates QoL

### ISSUE THREAD

**Issue by ConqAra** [Benjamin-Norton/BetterTrims#4]
Make armor templates (netherite upgrade excluded) have a durability of 4 so they can be used up 4 times, allowing for you to have a full trimmed set if you find one instead of disappointingly having it be used up on ONE piece of armor.

**Comment by Benjamin-Norton** [comment]
I'll add this as a configurable option. Since most templates come in pairs the default will be 2 uses per template allowing you to make a full set when you find any.
